$ANSIBLE_VAULT;1.1;AES256
65643137626330343338333334613037346339613537376336633062376365656330333862663863
3630633839353964393234363930396639646436356665620a323766633964613438636431666439
38333331343031646665383037336263633838343937623330633930333833656638366563316537
3535363062633633370a656339333035313666656261386263616665333030643532356330613630
38653133303763663361626230646338383136316661396632633733633664363263626164343564
32396162363866313736386235623962613937386531386663616437303663623062396336306666
61386562373736306462366431343165363565316364323934633230643864326437373035336238
36383165396666363439393333656632323763333235653230613533613537616332323632373534
39636337653737663434313661643334313232646562376461353366393532333764306264326436
62356637633562616261663835636530333833623737663034663736636465393132366361323432
33383031653530643637323733666431636535353435626364306164646630663437613366313339
62626631613466373165326239336534383736366264353335653033353865383234373732346137
31393232623761356631613935386661333563313761666131623161626563366133643733623364
37323233646331356635393164383830663164636634646136373137646665326531396133366563
393165333034386533346666613163306361
