---
# vars file for /home/ubuntu/project/roles/alb-switch
slack_enabled: true
region: "us-east-1"
phonebook_tg_green_arn: "arn:aws:elasticloadbalancing:us-east-1:623402582673:targetgroup/phonebook-tg-green/8e900298dcc18035"
phonebook_tg_blue_arn: "arn:aws:elasticloadbalancing:us-east-1:623402582673:targetgroup/phonebook-tg-blue/b4454bdb965fe14a"
subnet_ids: "subnet-ac01fba2"
security_group_id: "sg-04e77fce4ecd581f6"
alb_listener_arn: "arn:aws:elasticloadbalancing:us-east-1:623402582673:listener/app/phonebook-alb/83acea40370005ee/9af6db75022071f1"
slack_token: "{{ vault_slack_token }}"
slack_channel: "#ansible-project"
green_server_phonebook_ip: "34.238.191.86"
your_name: "Refia"